$global:COLMAP_DIR = "D:\Programs\colmap-x64-windows-cuda\bin"
$global:openMVG_DIR = "D:\Programs\openMVG\x64"
#$global:openMVS_DIR = "D:\Programs\openMVS\x64"
#$global:openMVS_DIR = "D:\Programs\openMVS\x64_CUDA"
$global:openMVS_DIR = "D:\Programs\openMVS\x64_MAX_CUDA_SUPPORT"